const db = require('../api/config/database');
const { sqlite, addColumnIfNotExists, isPostgres } = require('../api/config/database');

async function migrateStoriesToChapters() {
  const { rows: modulesWithOrphans } = await db.query(`
    SELECT DISTINCT ms.module_id
    FROM module_stories ms
    WHERE ms.chapter_id IS NULL
  `);

  for (const { module_id: moduleId } of modulesWithOrphans) {
    const { rows: chapterRows } = await db.query(
      `SELECT id FROM module_chapters
       WHERE module_id = $1 AND name = 'General'
       ORDER BY id ASC
       LIMIT 1`,
      [moduleId]
    );

    let chapterId = chapterRows[0]?.id;
    if (!chapterId) {
      const { rows: inserted } = await db.query(
        `INSERT INTO module_chapters
           (module_id, name, description, visible_to_students, display_order, created_at, updated_at)
         VALUES ($1, 'General', NULL, 1, 0, datetime('now'), datetime('now'))
         RETURNING id`,
        [moduleId]
      );
      chapterId = inserted[0]?.id;
    }

    if (chapterId) {
      await db.query(
        `UPDATE module_stories SET chapter_id = $1
         WHERE module_id = $2 AND chapter_id IS NULL`,
        [chapterId, moduleId]
      );
    }
  }
}

async function ensureModulesTablesPostgres() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS modules (
      id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name                  TEXT NOT NULL,
      description           TEXT,
      visible_to_students   INTEGER NOT NULL DEFAULT 0
                              CHECK (visible_to_students IN (0, 1)),
      created_at            TEXT NOT NULL DEFAULT (now()::text),
      updated_at            TEXT NOT NULL DEFAULT (now()::text)
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS module_chapters (
      id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      module_id             BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
      name                  TEXT NOT NULL,
      description           TEXT,
      visible_to_students   INTEGER NOT NULL DEFAULT 0
                              CHECK (visible_to_students IN (0, 1)),
      display_order         INTEGER NOT NULL DEFAULT 0,
      created_at            TEXT NOT NULL DEFAULT (now()::text),
      updated_at            TEXT NOT NULL DEFAULT (now()::text)
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS module_stories (
      id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      module_id             BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
      story_id              BIGINT NOT NULL REFERENCES "Stories"(id) ON DELETE CASCADE,
      visible_to_students   INTEGER NOT NULL DEFAULT 1
                              CHECK (visible_to_students IN (0, 1)),
      display_order         INTEGER NOT NULL DEFAULT 0,
      added_at              TEXT NOT NULL DEFAULT (now()::text),
      UNIQUE (module_id, story_id)
    )
  `);

  await db.query(`
    ALTER TABLE module_stories
    ADD COLUMN IF NOT EXISTS chapter_id BIGINT REFERENCES module_chapters(id) ON DELETE CASCADE
  `);

  await db.query(`CREATE INDEX IF NOT EXISTS idx_modules_visible ON modules (visible_to_students)`);
  await db.query(
    `CREATE INDEX IF NOT EXISTS idx_module_chapters_module ON module_chapters (module_id, display_order, id)`
  );
  await db.query(
    `CREATE INDEX IF NOT EXISTS idx_module_stories_module ON module_stories (module_id, display_order, id)`
  );
  await db.query(
    `CREATE INDEX IF NOT EXISTS idx_module_stories_chapter ON module_stories (chapter_id, display_order, id)`
  );
  await db.query(`CREATE INDEX IF NOT EXISTS idx_module_stories_story ON module_stories (story_id)`);

  await migrateStoriesToChapters();
}

async function ensureModulesTablesSqlite() {
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS modules (
      id                    INTEGER PRIMARY KEY AUTOINCREMENT,
      name                  TEXT NOT NULL,
      description           TEXT,
      visible_to_students   INTEGER NOT NULL DEFAULT 0
                              CHECK (visible_to_students IN (0, 1)),
      created_at            TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS module_chapters (
      id                    INTEGER PRIMARY KEY AUTOINCREMENT,
      module_id             INTEGER NOT NULL
                              REFERENCES modules(id) ON DELETE CASCADE,
      name                  TEXT NOT NULL,
      description           TEXT,
      visible_to_students   INTEGER NOT NULL DEFAULT 0
                              CHECK (visible_to_students IN (0, 1)),
      display_order         INTEGER NOT NULL DEFAULT 0,
      created_at            TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at            TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS module_stories (
      id                    INTEGER PRIMARY KEY AUTOINCREMENT,
      module_id             INTEGER NOT NULL
                              REFERENCES modules(id) ON DELETE CASCADE,
      story_id              INTEGER NOT NULL
                              REFERENCES Stories(id) ON DELETE CASCADE,
      visible_to_students   INTEGER NOT NULL DEFAULT 1
                              CHECK (visible_to_students IN (0, 1)),
      display_order         INTEGER NOT NULL DEFAULT 0,
      added_at              TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE (module_id, story_id)
    );

    CREATE INDEX IF NOT EXISTS idx_modules_visible
      ON modules (visible_to_students);
    CREATE INDEX IF NOT EXISTS idx_module_chapters_module
      ON module_chapters (module_id, display_order, id);
    CREATE INDEX IF NOT EXISTS idx_module_stories_module
      ON module_stories (module_id, display_order, id);
    CREATE INDEX IF NOT EXISTS idx_module_stories_story
      ON module_stories (story_id);
  `);

  addColumnIfNotExists(
    'module_stories',
    'chapter_id',
    'chapter_id INTEGER REFERENCES module_chapters(id) ON DELETE CASCADE'
  );
  await db.query(`
    CREATE INDEX IF NOT EXISTS idx_module_stories_chapter
      ON module_stories (chapter_id, display_order, id)
  `);

  await migrateStoriesToChapters();
}

async function ensureModulesTables() {
  if (isPostgres) {
    await ensureModulesTablesPostgres();
    console.log('✅ modules tables ready (modules, module_chapters, module_stories) [Postgres]');
    return;
  }

  await ensureModulesTablesSqlite();
  console.log('✅ modules tables ready (modules, module_chapters, module_stories) [SQLite]');
}

module.exports = { ensureModulesTables };
