const db = require('../api/config/database');
const { sqlite, isPostgres } = require('../api/config/database');

async function ensureBatchesTablesPostgres() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS batches (
      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name            TEXT NOT NULL UNIQUE,
      description     TEXT,
      status          TEXT NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'archived')),
      created_at      TEXT NOT NULL DEFAULT (now()::text),
      updated_at      TEXT NOT NULL DEFAULT (now()::text)
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS batch_students (
      batch_id        BIGINT NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
      student_id      BIGINT NOT NULL REFERENCES "Students"(id) ON DELETE CASCADE,
      added_at        TEXT NOT NULL DEFAULT (now()::text),
      PRIMARY KEY (batch_id, student_id)
    )
  `);

  await db.query(`CREATE INDEX IF NOT EXISTS idx_batches_status ON batches (status)`);
  await db.query(
    `CREATE INDEX IF NOT EXISTS idx_batch_students_batch ON batch_students (batch_id)`
  );
  await db.query(
    `CREATE INDEX IF NOT EXISTS idx_batch_students_student ON batch_students (student_id)`
  );
}

async function ensureBatchesTablesSqlite() {
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS batches (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      name            TEXT NOT NULL UNIQUE,
      description     TEXT,
      status          TEXT NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'archived')),
      created_at      TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS batch_students (
      batch_id        INTEGER NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
      student_id      INTEGER NOT NULL REFERENCES Students(id) ON DELETE CASCADE,
      added_at        TEXT NOT NULL DEFAULT (datetime('now')),
      PRIMARY KEY (batch_id, student_id)
    );

    CREATE INDEX IF NOT EXISTS idx_batches_status ON batches (status);
    CREATE INDEX IF NOT EXISTS idx_batch_students_batch ON batch_students (batch_id);
    CREATE INDEX IF NOT EXISTS idx_batch_students_student ON batch_students (student_id);
  `);
}

async function ensureBatchesTables() {
  if (isPostgres) {
    await ensureBatchesTablesPostgres();
    console.log('✅ batches tables ready (batches, batch_students) [Postgres]');
    return;
  }

  await ensureBatchesTablesSqlite();
  console.log('✅ batches tables ready (batches, batch_students) [SQLite]');
}

module.exports = { ensureBatchesTables };
