/** Flat professional colors per dashboard section (no gradients). */
export const DASHBOARD_SECTIONS = [
  {
    id: 'curriculum',
    label: 'Curriculum',
    path: '/curriculum',
    bgColor: '#DDD6FE',
    bgColorDark: '#5B21B6',
    textColor: '#5B21B6',
    textColorDark: '#EDE9FE',
    borderColor: '#7C3AED',
    borderColorDark: '#A78BFA',
    roles: ['admin'],
  },
  {
    id: 'principles',
    label: 'Principles',
    path: '/principles',
    bgColor: '#FDE68A',
    bgColorDark: '#92400E',
    textColor: '#78350F',
    textColorDark: '#FEF3C7',
    borderColor: '#D97706',
    borderColorDark: '#FBBF24',
    roles: ['admin'],
  },
  {
    id: 'users',
    label: 'Users',
    path: '/users',
    bgColor: '#BAE6FD',
    bgColorDark: '#0369A1',
    textColor: '#0C4A6E',
    textColorDark: '#E0F2FE',
    borderColor: '#0284C7',
    borderColorDark: '#38BDF8',
    roles: ['admin'],
  },
];
